wnbrb/wnb-rb-site

app/controllers/api/events_controller.rb
config/routes.rb
db/seeds.rb
spec/controllers/api/events_controller_spec.rb

Issue: https://github.com/wnbrb/wnb-rb-site/issues/18
Some decisions that we made:
- Changed `#past_get` to `#past` as it felt more natural. But am open to change back to `past_get` if that's what is preferred
- We create Event objects, because there hasn't been a clear decision for Factory Bot vs. Fixtures. Could be something to add later
- Changed the seed so that the second 'event' reflects the description of a past event in July

Add Controller action: API::EventsController #past

---

app/views/layouts/application.html.erb
app/views/layouts/mailer.html.erb
public/404.html
public/422.html
public/500.html

This PR addresses issue number 39
- Added `lang="en"` to all `html` tags with in the codebase
- Using `"en"` and not "en-US" as it is more widely recognized by screen readers

add lang attribute to all html tags

---

Gemfile
Gemfile.lock
app/javascript/packs/application.js
app/views/layouts/application.html.erb
app/views/site/sponsor_us.html.erb
package.json
yarn.lock

Our Heroku deployment currently has a few issues:
1. The styles are messed up on the sponsorship page
2. When you click a link, it loads a blank page, and then the content only renders on reload.
I've done some research on both of these issues. It looks like issue 1 is due to incorrectly naming the stylesheet pack tag in the `sponsor_us` view, and the second issue can be remedied by removing Turbolinks (which we're not using anyway).  
[Here's the SO post that led me to believe this was a Turbolinks issue](https://stackoverflow.com/questions/25463144/ruby-on-rails-pages-are-initially-blank-but-load-properly-on-refresh).
I've tested this on a different Heroku deployment so as not to spam our actual server and these changes made it look the same as my local environment!
You can see these …

Fix link and style issues on Heroku

---

Gemfile
Gemfile.lock
app/controllers/admin/events_controller.rb
app/controllers/application_controller.rb
app/models/user.rb
app/policies/application_policy.rb
app/policies/event_policy.rb
config/routes.rb
db/migrate/20211210204019_add_role_to_users.rb
db/schema.rb
spec/controllers/admin/events_controller_spec.rb
spec/factories/users.rb
spec/rails_helper.rb

This PR introduces the concept of user roles and adds the [Pundit gem](https://github.com/varvet/pundit) to implement authorization in this app.
The next set of issues we want to tackle all involve creating endpoints that should only be accessed by admin users. To unblock this work, I wanted to ensure we had a system for authorizing users. Each user can now be assigned an "admin" role, and Pundit will check that the user is an admin before performing any of the actions in the `Admin::EventsController`.

Support user roles and introduce Pundit gem for authorization

---

app/javascript/components/layout/Footer.jsx
app/javascript/components/layout/Header.jsx

Got some excellent feedback from @stefannibrasil that "Archive" is not very clear to non-native English speakers, so changing this to "Past Meetups" in the header and footer.

Rename "Archive" to "Past Meetups"

---

app/controllers/admin/events_controller.rb
app/views/admin/events/index.html.erb

This PR creates the admin events page (Issue https://github.com/wnbrb/wnb-rb-site/issues/23)
Co-authored with @jrussell416 
Notes: 
- This page includes _all events_ including both meetups and panels
- Added a few tailwind classes just for some basic styling
- Orders events in descending date order
- Adds placeholder links for add/edit/delete 
Questions/comments:
- Should the links be styled a particular way to look like buttons? Couldn't find an example of doing this anywhere else, but the issue does say they should be buttons.
- Any other information we should display or exclude from this page? Depending on the description length it might be a bit much for a table. We could truncate or exclude it if needed. 
- We may eventually want to paginate these events

Add admin events page

---

app/javascript/components/pages/Meetups.jsx
app/models/speaker.rb
config/initializers/rack.rb
db/migrate/20220120180256_add_image_url_to_speakers.rb
db/schema.rb
db/seeds.rb
spec/controllers/api/events_controller_spec.rb

This PR adds an `image_url` field to speakers and displays the image on the past meetups page  (Issue #58)
Co-authored by @lsaffel 
Moved the rack-mini-profiler to the bottom right corner so that it was less in the way on admin pages
Example in top left:

Add speaker image url

---

app/models/job.rb
db/migrate/20220118025538_add_image_url_to_jobs.rb
db/schema.rb
spec/factories/jobs.rb

This PR adds a column called `image_url` to the `jobs` table. This allows us to specify an image link for each job posting. When a company sends us a job, we can upload their image to storage somewhere (AWS?) and then display it in each job posting.

Add image_url to jobs table

---

app/controllers/api/jobs_controller.rb
app/javascript/components/pages/Jobs.jsx
app/models/job.rb
db/migrate/20220129221831_add_sponsorship_level_to_jobs.rb
db/schema.rb
db/seeds.rb
spec/controllers/api/jobs_controller_spec.rb
spec/factories/jobs.rb

This PR implements a couple of pretty small changes to the job board functionality and appearance
The first thing this PR does is order the jobs on the job board based on the sponsorship level of the companies that have posted them. Companies at higher sponsorship levels have their jobs come first.
To accomplish this, I:
* Added a `sponsorship_level` column to the jobs table
* On the backend, ordered jobs by the `sponsorship_level` column
* Changed the `as_json` functionality so sponsorship levels are not revealed to the frontend (this isn't strictly necessary, but I don't want to share this info if a company doesn't want it to be shared)
@jemmaissroff pointed out that this could make older listings seem outdated, even if they're not, so I've removed part of the UI.

Changes to Job Board

---

app/javascript/components/home/ExceedYourProfessionalGoalsSection.jsx
app/javascript/components/home/GiveSupportSection.jsx
app/javascript/components/home/JoinOurWelcomingCommunitySection.jsx
app/javascript/stylesheets/page.css

We forgot to actually link the code of conduct on the home page 😆 This PR fixes that.

Fix the code of conduct link on the homepage

---

app/controllers/api/events_controller.rb
config/routes.rb
spec/controllers/api/events_controller_spec.rb

This PR is to add an API endpoint and the according routes returning a JSON response to get the upcoming meetup into the api/events_controller
**Acceptance Criteria**
in the console create a new meetup with a speaker
```
august_meetup = Meetup.create(title: 'August Meetup', location: 'virtual', date: DateTime.new(2022, 8, 31, 16).utc)
speaker = Speaker.create(name: 'Speaker Name', tagline: 'Software Developer', bio: 'Lorem Ipsum', image_url: 'https://picsum.photos/200')
EventSpeaker.create(event: august_meetup, speaker: speaker, talk_title: 'Some talk title', talk_description: 'Lorem Ipsum')
```
Run Forman with `forman start`
Go to the url `http://localhost:5000/api/events/upcoming`
Ilafont & dsouza worked on Issue #19 
Closes #19

Add API endpoint for upcoming event

---

Gemfile
Gemfile.lock
config/application.rb
lib/tasks/job_board.rake
spec/tasks/job_board/digest_spec.rb

I was attempting to set up Heroku scheduler to run the job board digest job every Monday. Of course, it doesn't implement that behavior 😆 Instead, you can only set it to run every day at a certain time. Because it's free, I still think we should use it, so I've put a hacky check in the task itself such that it will only run on Mondays.

Only run job board digest task on Mondays

---

app/controllers/api/events_controller.rb
app/controllers/site_controller.rb
app/javascript/components/SpeakersList.jsx
app/javascript/components/icons/Microphone.jsx
app/javascript/components/layout/Footer.jsx
app/javascript/components/layout/Header.jsx
app/javascript/components/pages/Meetups.jsx
app/javascript/components/pages/PastMeetup.jsx
app/javascript/datasources/index.js
app/javascript/packs/past_meetup.jsx
app/views/site/past_meetup.erb
config/routes.rb
db/seeds.rb

Adds a past meetup page, Issue #7
Displays the video from the `panel_video_link` on an event.  I'm not sure how more than one video per event would be stored as this field doesn't seem to be an array?  But please let me know if I've misunderstood.
In the design these are in two columns, but I found this didn't work very well when there were more than 2 speakers, so I've used the speaker listing from the design for the Upcoming Meetup (single column).  Happy to change if this isn't ok!

Past meetup page

---

.github/workflows/test.yml

The rubocop-discourse gem added more linters we were not using locally, additionally installing these gems was already in our Gemfile.
If we want to add in the linters from the rubocop-discourse gem, we should add the inherits_gem piece from the readme after adding the gem to our gemfile https://github.com/discourse/rubocop-discourse

Fix rubocop failure in test workflow

---

Procfile
Procfile.dev
README.md

Fixes #96
This PR adds a `release` phase to the Procfile file per Heroku Release phase.
Heroku documentation can be found here.
https://devcenter.heroku.com/articles/release-phase#specifying-release-phase-tasks
One consideration / suggestion I would like input on, would be if we'd like to split up the Procfile.dev into
two files. It's often common to have a Procfile.dev file for use during development, and a Procfile to specify
the processes for Production. I would like to create a Procfile.dev with the rails server process and
webpacker, and remove the bin/webpack-dev-server process from the Procfile (so the production procfile would
only be the rails server / release phase)

Automatically run db migrations on Heroku deploy

---

spec/tasks/job_board/digest_spec.rb

Short version
These specs were failing when I ran them locally. `Date.today` makes Timecop act goofy sometimes. This change makes them pass when run locally on a system west of Eastern Time.
Long version
When Timecop receives a `Date`, it converts it to a time once using a method (`ActiveSupport::TimeZone#local`) that uses the time zone configured in `application.rb` (Eastern Time) and then again using a method (`Time#localtime`) that uses the system time zone.
So the `Date.today.last_week(:monday)` argument passed to Timecop gets transmuted like this:
`Mon, 23 May, 2022` (no time zone) ➡️ `Mon, 23 May 2022 00:00:00.000000000 EDT -04:00` (application time zone) ➡️ `2022-05-22 23:00:00 -0500` (system time zone; if your system's on Central Time, now Timecop thinks it's Sunday)
`Time.now` …

Replace Date.today with Time.now so Timecop won't get confused

---

spec/controllers/api/events_controller_spec.rb

Run `bundle exec rspec` on the main branch and you'll see several failing tests. This is one of them: 
```
1) Api::EventsController GET #upcoming correctly gets upcoming events
Failure/Error: expect(body['data']['2022'].count).to eq(2)
expected: 2
got: 1
(compared using ==)
```
All of the failing tests are caused by the same problem. The event date set as upcoming events has passed, which means to the test, the event is now in the past, making the tests fail. 
Using TimeCop, this change freezes the DateTime for these tests to make it more resilient for future.
The DateTime picked was arbitrary - just one that works for the current test data.

Freeze time for event-related tests

---

app/javascript/components/pages/Donate.jsx
app/javascript/components/pages/Home.jsx
app/javascript/components/pages/Jobs.jsx
app/javascript/components/pages/JobsAuthenticate.jsx
app/javascript/components/pages/Meetups.jsx
app/javascript/components/pages/PastMeetup.jsx
app/javascript/components/pages/SponsorUs.jsx
package.json
yarn.lock

Resolves: https://github.com/wnbrb/wnb-rb-site/issues/75
Because of how the header (in application.erb) is set up, we cannot retroactively set the `title` once the page's body / javascript script is rendered. Anyway, I used `react-helmet`'s [Helmet component](https://github.com/nfl/react-helmet) for in each of the page component to set the titles. 
Examples:

Add more specific page titles 

---

app/javascript/components/pages/Meetups.jsx
db/seeds.rb

Fixes: https://github.com/wnbrb/wnb-rb-site/issues/130
It seems that the bar was misaligned because some months have longer words than others. Increasing the width of the little month box fixed it!
To be able to test this locally I added another meetup event to the seeds. I created it for September because that's the month with the most characters.
Before and after shots 💅 
**Before: grey bar is broken up**
**After: all in one line!**

Fix: past meetups page grey bar alignment issue

---

db/migrate/20221208080716_add_links_to_speakers.rb
db/schema.rb
db/seeds.rb
spec/controllers/api/events_controller_spec.rb

Related: https://github.com/wnbrb/wnb-rb-site/issues/124
- added a jsonb column for the speaker links
Question:
1) I called the new column `links` and I don't love it. Because it's a plural word it makes me think that the data should be an array. But it's a hash/object with a structure of `{social_media_platform: 'link-to-profile-on-platform'}`. What do you think?
Better ideas for a name are welcome!
Next steps:
I'd like to implement the frontend in a separate PR. More info (with request for feedback) added to the issue. https://github.com/wnbrb/wnb-rb-site/issues/124

Add speaker links to speaker table

---

spec/rails_helper.rb
spec/support/devise.rb

Move devise helpers from `/spec/rails_helper.rb` to `/spec/support/devise.rb`

move devise helpers into support file

---

app/javascript/components/PageTitleWithContainer.jsx
app/javascript/components/layout/Footer.jsx
app/javascript/components/layout/Header.jsx
app/javascript/components/meetups/MeetUp.jsx
app/javascript/components/meetups/MonthSection.jsx
app/javascript/components/meetups/YearSection.jsx
app/javascript/components/pages/Meetups.jsx
app/javascript/packs/application.js
app/javascript/stylesheets/page-title.scss

close #190 
- Mobile
- Desktop

Update meetup page

---

Gemfile
Gemfile.lock
spec/controllers/api/events_controller_spec.rb
spec/support/time_helpers.rb
spec/tasks/job_board/digest_spec.rb

Since Rails 4.1, Active Support includes its own timehelpers, rendering the timecop gem unnecessary. This PR removes the dependency on timecop and updates the codebase to utilize the built-in timehelpers provided by Active Support. This change improves the efficiency and maintainability of the codebase.

Remove unnecessary dependency on the timecop gem

---

Gemfile
app/javascript/components/pages/PastMeetup.jsx
app/models/talk.rb
spec/models/talk_spec.rb

- `https://www.youtube.com/embed/VIDEO_ID` is the[ required format ](https://developers.google.com/youtube/player_parameters#Manual_IFrame_Embeds)for the iframe tag from PastMeetup.jsx. This PR includes an error message that appears when the URL doesn't match.

Verify embedded YouTube videos url link

---

Gemfile.lock
app/controllers/application_controller.rb
app/javascript/components/pages/NotFound.jsx
app/javascript/packs/not_found.jsx
app/javascript/stylesheets/not_found.scss
app/views/application/not_found.html.erb
config/routes.rb
spec/system/visit_site_pages_spec.rb

Issue #66
This pull creates a custom not found page consistent with the theme of the site. 
I modified the existing application#render_not_found method and added a views/application directory to hold the view. I'm not sure if that is how you would like it. Maybe it would be better in the views/site directory? Let me know and I can change it. 
I also added a test. Again, not sure where the best place for it is.

66 add custom 404 page

---

app/javascript/components/layout/Footer.jsx
app/javascript/components/layout/Header.jsx
app/javascript/stylesheets/header.scss
config/routes.rb
spec/system/visit_site_pages_spec.rb

We are revamping our jobs program. In the meantime, I think we should remove our now-defunct jobs page in order not to confuse people.
This PR removes the routes to the job board and links in the menu and footer. I've kept all the underlying code (models, controllers, views) because I think we'll do something else with them, but I'll remove them if not.

Temporarily remove the job board

---

Makefile

This commit adds two commands to the `setup` target:
- `yarn build`
- `yarn build:css`
This ensures that RSpec runs pass on an initial setup of the WNB project if the project hasn't been run yet (ex: via foreman)

Builds yarn assets as part of setup commands

---

app/controllers/site_controller.rb
app/javascript/components/layout/Footer.jsx
app/javascript/components/layout/Header.jsx
app/javascript/components/pages/SponsorUs.jsx
app/javascript/packs/sponsor_us.jsx
app/views/layouts/application.html.erb
app/views/site/sponsor_us.html.erb
config/routes.rb

This PR adds a sponsorship section back to our website with a pricing table generated by Stripe. It also modifies the header to make sponsoring the second call to action, while moving the "donate" button to the left side.

Add new "Sponsor Us" page

---

app/javascript/components/pages/SponsorUs.jsx

This PR adds links for sponsors to pay us for posting a job in our Slack or just making a corporate donation.
@luciagirasoles Please feel free to correct any of my React and styles here.

Added hiring and donation link to sponsorship page

---

app/javascript/components/pages/PastMeetup.jsx
spec/system/visit_site_pages_spec.rb

modify the meetup page to display these links for each speaker if they are available, actually Im not really sure which icon should we use for "website" and "other", hence I use globe as website and link for other, need your feedback on this (the social media is based on speaker model), so it shows like this :
actually this PR changes kinda same one with https://github.com/wnbrb/wnb-rb-site/pull/227, but with some changes.
Look forward for the feedback.

Add links to speaker in meetup page

---

Gemfile.lock
app/models/speaker.rb

For some reason, the each_value line in DB seeds broke on my system, but doesn't seem to affect anyone else. Not sure if this is the right fix, because I don't understand how it works on other platforms. Approved by Emily.

Changes needed for Seed run (possibly Mac only?)

---

.erb_lint.yml
Gemfile
Gemfile.lock
yarn.lock

- Added the `erb-lint` gem to the project for linting `.erb` files
- Created a `.erb_lint.yml` file with default linters enabled
- Verified the linter runs successfully on all `.erb` files
Resolves #175

Add erb-lint gem and configuration file for linting ERB files

---

app/views/site/join_us.html.erb

This PR addresses formatting issues identified after implementing the ERB linter in https://github.com/wnbrb/wnb-rb-site/pull/264, which was introduced to address https://github.com/wnbrb/wnb-rb-site/issues/175.
This fix replaces the js_tag with an inline script tag
**Before**
**After**

change js tag to inline script

---

.gitignore
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
app/views/layouts/mailer.html.erb

This PR addresses formatting issues identified after implementing the ERB linter in [PR #264 - Add erb-lint gem and configuration file for linting ERB files](https://github.com/wnbrb/wnb-rb-site/pull/264), which was introduced to address [Issue #175 - Add lint for erb files](https://github.com/wnbrb/wnb-rb-site/issues/175).
This fix removed '/'  in closing tag of void elements
Before
After

Fix void element issues from running erb-lint

---

app/views/admin/events/_form.html.erb
app/views/admin/events/form/_card_talk.html.erb
app/views/admin/speakers/_form.html.erb
app/views/admin/speakers/edit.html.erb
app/views/admin/speakers/index.html.erb
app/views/admin/speakers/index/_speaker_links.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/layouts/admin.html.erb
app/views/site/join_us.html.erb

This PR addresses formatting issues identified after implementing the ERB linter in [PR #264 - Add erb-lint gem and configuration file for linting ERB files](https://github.com/wnbrb/wnb-rb-site/pull/264), which was introduced to address [Issue #175 - Add lint for erb files](https://github.com/wnbrb/wnb-rb-site/issues/175).
This fix adjusted spacing by adding or removing spaces after code to comply with linter rules
**Before (lack of  space before `%>)**
**After ( space added)**

Fix spacing issues in ERB files identified by erb-lint

---

app/views/layouts/application.html.erb

This PR addresses formatting issues identified after implementing the ERB linter in https://github.com/wnbrb/wnb-rb-site/pull/264, which was introduced to address https://github.com/wnbrb/wnb-rb-site/issues/175.
This fix added quotes around attribute value
Before
After

add quotes to class attribute in <body> tag

---

app/javascript/components/meetups/EventsCalendar.jsx
app/javascript/components/meetups/MeetUp.jsx
app/javascript/components/pages/Meetups.jsx

- Update the past meetup section to display the most recent meetups to the oldest in descending order.
- Update the cards in the calendar component to display the meetings in descending order.

291 sort past meetups from most recent to oldest

---

.github/workflows/deploy.yml
.github/workflows/test.yml

- Deploy workflow
- Tests workflow
The ubuntu-20.04 runner was officially deprecated and retired by GitHub on April 15, 2025, causing workflows relying on it to fail. This migration ensures that our CI/CD pipelines remain functional and future-proof.

298 update GitHub actions workflow from ubuntu 2004 to ubuntu 2204

---

app/controllers/application_controller.rb
app/javascript/stylesheets/community.scss

**Summary:**
This PR updates the render_not_found method in ApplicationController to handle non-HTML request formats more gracefully. Previously, requests with Accept: application/json or other formats would raise a MissingTemplate error because the view only existed for HTML.
**How to Reproduce the Bug (Before This Fix)**
curl -H "Accept: application/json" http://localhost:3000/nonexistent
=> raises ActionView::MissingTemplate
**How to Verify the Fix**
curl -H "Accept: text/html" http://localhost:3000/nonexistent
=> React 404 page renders as expected
curl -H "Accept: application/json" http://localhost:3000/nonexistent
=> {"error": "Not Found"}
curl -H "Accept: application/xml" http://localhost:3000/nonexistent -i
=> HTTP 404 with no body
**Additional Fix:**
Also includes a minor CSS …

Graceful 404 Handling for JSON and Other Formats

---

.github/workflows/test.yml

Potential fix for [https://github.com/wnbrb/wnb-rb-site/security/code-scanning/6](https://github.com/wnbrb/wnb-rb-site/security/code-scanning/6)
The best way to fix this problem is to explicitly set the minimal required permissions for the workflow's use of the GITHUB_TOKEN. Since the job only checks out code and runs install/build/test commands, it does not need write access—`contents: read` suffices.  
To do this, add a `permissions:` block to the workflow. This can be at the workflow root (above the `jobs:` key), applying to all jobs, or directly under the individual job (`test:` in this case).  
For clarity and conciseness, it is recommended to set it at the workflow root level so all jobs inherit it (unless there are jobs requiring wider permissions, which is not the case here). …

Potential fix for code scanning alert no. 6: Workflow does not contain permissions
